version: "3.8"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: task_manager_app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules

